# World config
id: 1 # Jiva
host: "127.0.0.1"
port: 3001

# Mysql config
mysql:
  host: "127.0.0.1"
  port: 3306
  dbname: "rubis_world"
  user: "root"
  password: ""
io:
  host: "127.0.0.1"
  port: 5050
  protocol: 'http'

# Debug mode
debug: false