# World config
id: 1 # Jiva
host: "127.0.0.1"
port: 3001

# Mysql config
mysql:
  host: "127.0.0.1"
  port: 3306
  dbname: "rubis_world"
  user: "root"
  password: ""
http:
  host: "127.0.0.1"
  port: 81
  password: "mySecretPassword"

# Debug mode
debug: false